

-- 1)
CREATE OR REPLACE VIEW Advisor_Selection
AS
SELECT ID , NAME , DEPT_NAME
FROM
INSTRUCTOR;

SELECT * FROM Advisor_Selection;





-- 2)
CREATE OR REPLACE VIEW Student_Count
AS
SELECT NAME , COUNT(S_ID) AS COUNT
FROM Advisor_Selection, Advisor
WHERE Advisor_Selection.ID = Advisor.I_ID
GROUP BY NAME;

SELECT * FROM Student_Count;



-- 3)a)
CREATE ROLE STUDENT ;
GRANT SELECT ON ash200042123.ADVISOR TO STUDENT ;
GRANT SELECT ON  ash200042123.COURSE TO STUDENT ;


-- 3)b)
CREATE ROLE COURSE_TEACHER ;
GRANT SELECT ON ash200042123.STUDENT TO COURSE_TEACHER;
GRANT SELECT ON ash200042123.COURSE TO COURSE_TEACHER ;


-- 3)c)
CREATE ROLE DEPT_HEAD;
GRANT COURSE_TEACHER TO DEPT_HEAD;
GRANT INSERT ON ash200042123.INSTRUCTOR to DEPT_HEAD;

/*insert into instructor values ('12547', 'Jimmy', 'Elec. Eng.', '80000');*/




/*3)d)*/
CREATE ROLE ADMINISTRATOR ;
GRANT SELECT ON ash200042123.DEPARTMENT TO ADMINISTRATOR;
GRANT SELECT ON  ash200042123.INSTRUCTOR TO ADMINISTRATOR;
GRANT UPDATE (BUDGET) ON ash200042123.DEPARTMENT TO ADMINISTRATOR;




CREATE USER ASHFAQ IDENTIFIED BY cse4308;
GRANT STUDENT TO ASHFAQ;
GRANT CREATE SESSION TO ASHFAQ; 


CREATE USER RIDUN IDENTIFIED BY cse4308;
GRANT COURSE_TEACHER TO RIDUN;
GRANT CREATE SESSION TO RIDUN; 



CREATE USER SHUVRO IDENTIFIED BY cse4308;
GRANT ADMINISTRATOR TO SHUVRO;
GRANT CREATE SESSION TO SHUVRO; 


CREATE USER SHOYEB IDENTIFIED BY cse4308;
GRANT DEPT_HEAD TO SHOYEB;
GRANT CREATE SESSION TO SHOYEB;

/*After logging in as student*/
SELECT * FROM ash200042123.ADVISOR;
SELECT * FROM ash200042123.COURSE;
SELECT * FROM ash200042123.DEPARTMENT; /*CANNOT be accessed*/


/*After logging in as course teacher*/
SELECT * FROM ash200042123.STUDENT;
SELECT * FROM ash200042123.COURSE;
SELECT * FROM ash200042123.ADVISOR; /*CANNOT be accessed*/

/*After logging in as department head*/
insert into ash200042123.instructor values ('54321', 'Laal', 'Biology', '100000');


/*After logging in as administrator*/
SELECT * FROM ash200042123.DEPARTMENT;
SELECT * FROM ash200042123.INSTRUCTOR;

UPDATE ash200042123.DEPARTMENT
SET BUDGET='150000'
WHERE DEPT_NAME = 'Elec. Eng.';

UPDATE ash200042123.DEPARTMENT
SET BUILDING='AB2'
WHERE DEPT_NAME = 'Elec. Eng.';/*CANNOT be updated*/
