

CREATE TABLE ACCOUNT
(
    ACCOUNT_NO char(5),
    BALANCE number NOT NULL,
    CONSTRAINT PK_ACCOUNT_NO PRIMARY KEY (ACCOUNT_NO)
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_NO char(5),
    CUSTOMER_NAME varchar2(20) NOT NULL,
    CUSTOMER_CITY varchar2(10),
    CONSTRAINT PK_CUSTOMER_NO PRIMARY KEY (CUSTOMER_NO)
);

CREATE TABLE DEPOSITOR
(
    ACCOUNT_NO char(5),
    CUSTOMER_NO char(5),
    CONSTRAINT PK_ACC_CUSTOMER PRIMARY KEY (ACCOUNT_NO,CUSTOMER_NO)
);


ALTER TABLE CUSTOMER ADD DATE_OF_BIRTH DATE;

ALTER TABLE ACCOUNT MODIFY BALANCE number(12,2);

ALTER TABLE DEPOSITOR RENAME COLUMN ACCOUNT_NO TO A_NO;
ALTER TABLE DEPOSITOR RENAME COLUMN CUSTOMER_NO TO C_NO;

ALTER TABLE DEPOSITOR RENAME TO DEPOSITOR_INFO;

ALTER TABLE DEPOSITOR_INFO ADD CONSTRAINT FK_DEPOSITOR_ACCOUNT FOREIGN KEY (A_NO) REFERENCES ACCOUNT(ACCOUNT_NO);
ALTER TABLE DEPOSITOR_INFO ADD CONSTRAINT FK_DEPOSITOR_CUSTOMER FOREIGN KEY (C_NO) REFERENCES CUSTOMER(CUSTOMER_NO);





INSERT INTO ACCOUNT VALUES('12345',70000);
INSERT INTO ACCOUNT VALUES('23456',120000);
INSERT INTO ACCOUNT VALUES('34567',100000);
INSERT INTO ACCOUNT VALUES('14567',7000);


INSERT INTO CUSTOMER VALUES('10000','ASHFAQ','KHL','30-JAN-2000');
INSERT INTO CUSTOMER VALUES('10001','SHOYEB','DHK','30-AUG-2001');
INSERT INTO CUSTOMER VALUES('20001','SHUVRO','CTG','09-JAN-1999');

INSERT INTO DEPOSITOR_INFO VALUES('23456','10000');
INSERT INTO DEPOSITOR_INFO VALUES('34567','20001');
INSERT INTO DEPOSITOR_INFO VALUES('12345','10001');
INSERT INTO DEPOSITOR_INFO VALUES('14567','10000');




SELECT ACCOUNT_NO 
FROM ACCOUNT
WHERE BALANCE<100000;


SELECT CUSTOMER_NAME
 FROM CUSTOMER
WHERE CUSTOMER_CITY='KHL';


SELECT CUSTOMER_NO
 FROM CUSTOMER
WHERE (CUSTOMER_NAME like '%A%') or (CUSTOMER_NAME like '%a%');


SELECT DISTINCT A_NO
 FROM DEPOSITOR_INFO;


SELECT *
FROM ACCOUNT,DEPOSITOR_INFO;


SELECT *
FROM CUSTOMER NATURAL JOIN DEPOSITOR_INFO;


SELECT DISTINCT CUSTOMER_NAME, CUSTOMER_CITY
FROM CUSTOMER, DEPOSITOR_INFO
WHERE CUSTOMER.CUSTOMER_NO=DEPOSITOR_INFO.C_NO;


SELECT DISTINCT CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_CITY,DATE_OF_BIRTH
FROM CUSTOMER, ACCOUNT, DEPOSITOR_INFO
WHERE ACCOUNT.BALANCE>1000 AND DEPOSITOR_INFO.C_NO=CUSTOMER.CUSTOMER_NO AND ACCOUNT.ACCOUNT_NO=DEPOSITOR_INFO.A_NO;


SELECT ACCOUNT_NO,BALANCE
FROM CUSTOMER, ACCOUNT, DEPOSITOR_INFO
WHERE (DEPOSITOR_INFO.C_NO=CUSTOMER.CUSTOMER_NO AND ACCOUNT.ACCOUNT_NO=DEPOSITOR_INFO.A_NO)
 AND ((ACCOUNT.BALANCE>5000 AND ACCOUNT.BALANCE<10000) OR CUSTOMER.CUSTOMER_CITY='DHK') ;

